### ISSUE TITLE
Filter Out RDM Discovery Messages

### ISSUE THREAD

**Issue by sammysmallman** [ETCLabs/ETCDmxTool#22]
Using the "Sniffer" to interrogate RDM traffic I would love the ability to filter out discovery messages from the table so that I can easily see all the other messages more easily. This would be particularly useful when I have a controller doing device discovery pretty aggressively...

**Comment by docsteer** [comment]
Regex Searching (#29) is included in the 2.1.0 build, which allows you to filter messages by type
