### ISSUE TITLE
Invalid Message

### ISSUE THREAD

**Issue by sammysmallman** [ETCLabs/ETCDmxTool#27]
A controller generated message with a Port ID of 0 should indicate as invalid.
![Capture](https://user-images.githubusercontent.com/8962989/165289213-4f34612d-0412-42bd-a00a-1b92a5d1ce11.PNG)

**Comment by marcusbirkin** [comment]
There is also no range validation checks on Sub Start Code, Response Type, and Sub device.

Of note, the original issues of the RDM spec had typos in the given example frames where a Port ID of "0" was valid. However the explanatory text gave the correct allowable range of 0x01-0xFF
